### ISSUE TITLE
请问支持php7吗？

### ISSUE THREAD

**Issue by grayguest** [LoRexxar/Cobra-W#22]
RT，另外想主要对php代码做分析，和rips0.55比较，哪个在php上面的表现性能比较好呢？

**Comment by LoRexxar** [comment]
支持php7的

rips0.55基本是个垃圾，如果不缺钱可以试试rips收费版

我这个还行吧，有些缺陷一直没来得及改

**Comment by grayguest** [comment]
感谢表哥回复，现在主要是对php代码做分析，也在p牛星球里面看到你了，看到你们说针对php某款框架做专业的修改可以提高不少效率，这周就看看你这个啦，希望能继续丰富啊，嘎嘎。

**Comment by LoRexxar** [comment]
如果有问题可以及时提issue，过段时间会继续更新的

**Comment by tinysheepyang** [comment]
扫描PHP时可以指定PHP版本吗，比如PHP7三目运算是??,PHP5中是isset($var) ? $var: 返回值，默认扫描到三目运算时报语法错误了
