### ISSUE TITLE
cobra-w对比cobra

### ISSUE THREAD

**Issue by grayguest** [LoRexxar/Cobra-W#23]
### System and Python Environment

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`|CentOS7|
|Python|`python -V`|Python 3.7.0|
|Cobra|`python cobra.py`|cobra-w v1.1.0|

### Description
对比cobra v2.0.0-alpha.5，最明显的差异是cobra-w没有扫描出dvwa中的命令注入相关的漏洞，而优势是cobra-w扫描出了2处sqli，分别对应路径为sqli/ sqli_blind/

### Steps to Reproduce
cobra-w
1. python cobra.py -t /root/php/dvwa/vulnerabilities/ -f html -o ./cobra_w_dvwa.html
![ACGLFS.png](https://s2.ax1x.com/2019/03/11/ACGLFS.png)

cobra
1. python cobra.py -t /root/php/dvwa/vulnerabilities/ -f json -o ./cobra_dvwa.json
![ACGOJg.png](https://s2.ax1x.com/2019/03/11/ACGOJg.png)

**Expected behavior:** 期望cobra-w能包含cobra的关键性漏洞

**Actual behavior:** 未包含最关键的高危漏洞命令注入

**Comment by LoRexxar** [comment]
感谢issue，我去下载一份dvwa测试一下

**Comment by LoRexxar** [comment]
fixed，感谢issue
