### ISSUE TITLE
define变量检测读取警告

### ISSUE THREAD

**Issue by yida223** [LoRexxar/Cobra-W#69]
### System and Python Environment
centos7腾讯云服务器
![image](https://user-images.githubusercontent.com/42206940/78468383-131a5700-774a-11ea-8bbd-5a46f1e181b1.png)

|Item|Tooltip|Value|
|---|---|---|
|System|`uname -a`||
|Python|`python -V`||
|Cobra|`python cobra.py`||

### Description

[Description of the bug or feature]
运行报错
![image](https://user-images.githubusercontent.com/42206940/78468396-380eca00-774a-11ea-8167-35d234cf1b99.png)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

**Comment by LoRexxar** [comment]
这不是个警告吗，哪里报错了...

**Comment by LoRexxar** [comment]
不过我挺好奇这个警告的，这部分是检测define常量的。

你能找一下对应扫描文件的define部分代码吗，我想看看是因为什么报错的。

**Comment by yida223** [comment]
我是在扫描一个CMS的源码报的错，这是那个源码下载地址https://www.mycodes.net/97/3638.htm
